TrainingArguments:
  num_train_epochs: 1
  warmup_steps: 10 # Much smaller for quick training
  per_device_train_batch_size: 2 # Slightly larger batch
  weight_decay: 0.01
  logging_steps: 5 # More frequent logging
  evaluation_strategy: steps
  eval_steps: 20 # Evaluate more frequently
  save_steps: 1000000
  gradient_accumulation_steps: 4 # Smaller accumulation
  max_steps: 50 # LIMIT TOTAL STEPS for quick testing
